app/controllers/appearances_controller.rb
app/controllers/artists_controller.rb
app/controllers/concerts_controller.rb
app/controllers/dislikes_controller.rb
app/controllers/likes_controller.rb
app/controllers/users_controller.rb
app/controllers/videos_controller.rb
app/models/appearance.rb
app/models/artist.rb
app/models/concert.rb
app/models/dislike.rb
app/models/like.rb
app/models/user.rb
app/models/video.rb
db/migrate/20150416202006_create_concerts.rb
db/migrate/20150416202127_create_appearances.rb
db/migrate/20150416202150_create_artists.rb
db/migrate/20150416202200_create_videos.rb
db/migrate/20150416202206_create_users.rb
db/migrate/20150416202210_create_likes.rb
db/migrate/20150416202215_create_dislikes.rb

adding migrations

---

db/schema.rb
log/development.log

added schema

---

app/models/artist.rb
app/models/concert.rb
db/seeds.rb
log/development.log

-Ryan
Modified models to make artist and concert association through appearances table.

Initial concert creation with artist associations

---

.gitignore

added the .gitignore file

---

app/controllers/application_controller.rb
app/controllers/authentication_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/views/users/new.html.erb
app/views/users/show.html.erb
app/views/users/signin.html.erb
config/routes.rb
db/seeds.rb

added authentication for the application

added authentication

---

app/controllers/artists_controller.rb
app/controllers/concerts_controller.rb
app/controllers/users_controller.rb
app/views/artists/index.html.erb
config/routes.rb

adding the search functionality on index page

adding the search functionality on index page

---

app/views/layouts/application.html.erb

fonts to layout page

---

app/assets/stylesheets/application.css
app/views/users/_searchform.html.erb

style search bar/submit button/add placeholder

style search bar/submit button

---

app/controllers/artists_controller.rb
app/views/users/_searchform.html.erb

adding the autopopulate functionality for the search bar

adding the autopopulate functionality for the search bar

---

app/assets/javascripts/animation.js
app/assets/javascripts/application.js
app/views/users/_searchform.html.erb
app/views/users/index.html.erb

added files that might cause merge conflicts

added files that might cause merge conflicts

---

app/assets/javascripts/animation.js
app/assets/javascripts/indexpage.js
app/assets/stylesheets/index.css
app/views/layouts/application.html.erb
public/animate.css

adding css changes for the index page animation

adding css changes for the index page animation

---

app/views/users/_signin.html.erb
app/views/users/_signup.html.erb

added videos for the index page

added videos for the index page

---

app/assets/stylesheets/application.css
app/views/users/index.html.erb

fixed signup button

---

app/assets/stylesheets/application.css
app/views/users/index.html.erb

video id change

---

app/assets/javascripts/animation.js
app/assets/stylesheets/application.css
app/assets/stylesheets/masthead.css
app/views/users/index.html.erb

Malc sunday

---

app/assets/stylesheets/application.css
app/views/users/_searchform.html.erb
app/views/users/index.html.erb

moved things around on index

---

app/assets/javascripts/animation.js
app/assets/stylesheets/application.css
app/assets/stylesheets/masthead.css
app/views/users/index.html.erb

Malc monday

---

app/assets/javascripts/typeahead.js
app/assets/stylesheets/application.css

edit suggestion bar

---

app/assets/javascripts/concert_show.js
app/controllers/videos_controller.rb
app/views/concerts/_upload.html.erb
app/views/concerts/_videos.html.erb

Rails and Ajax implementation of Like button restriction.
A user may only like and dislike a particular video once.

Like and Dislike BTN single votes

---

app/assets/javascripts/concert_show.js
app/controllers/attends_controller.rb
app/controllers/concerts_controller.rb
app/controllers/likes_controller.rb
app/models/attend.rb
app/models/concert.rb
app/models/user.rb
app/views/concerts/_upload.html.erb
app/views/concerts/show.html.erb
db/migrate/20150420231605_create_attends.rb
db/schema.rb

Created:
- attends migration
- attend model
- attends_controller
Added:
- changes to user and concert models for association.
The association works. User can now find all concerts of attendance by **User.attends**
Concerts find total attendance by **concert.attends.count**

Added inital attendance features.

---

app/assets/javascripts/animation.js
app/views/concerts/_videos.html.erb
app/views/concerts/show.html.erb

fixed home/concert show bugs

---

app/models/video.rb

added has many comments to video model

video has many comments model

---

app/controllers/followings_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/followings/originators.html.erb
app/views/followings/targets.html.erb
app/views/users/show.html.erb
config/routes.rb
db/seeds.rb

completed the follow feature

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/_dashboard.html.erb
app/views/users/show.html.erb

added user likes, user attended concerts to user Dash

added user likes, user attended concerts to user Dash

---

app/controllers/application_controller.rb
app/views/users/_dashboard.html.erb
db/seeds.rb

added gravater image feature for the profile picture

added gravater image feature for the profile picture

---

app/controllers/followings_controller.rb
app/controllers/users_controller.rb
app/models/following.rb
app/views/followings/originators.html.erb
app/views/followings/targets.html.erb
app/views/users/show.html.erb

added the follow count functionality

added the follow count functionality

---

app/assets/stylesheets/application.css

change suggestion color

---

app/views/users/index.html.erb

Update index background video.

Remove showgoer webm from index

---

app/assets/javascripts/animation.js
app/assets/stylesheets/application.css
app/assets/stylesheets/concert-videos.css
app/assets/stylesheets/masthead.css
app/controllers/users_controller.rb
app/controllers/videos_controller.rb
app/views/artists/show.html.erb
app/views/concerts/_videos.html.erb
app/views/concerts/show.html.erb
app/views/users/index.html.erb
db/seeds.rb

Add new video/make edits to concert show

Add videos

---

Gemfile
Gemfile.lock

Added 12 factor for heroku logs

Add 12factor for heroku logs

---

.buildpacks

Add buildpacks feature

---

config/environments/production.rb

Change production env

---

db/seeds.rb

Fix error from seeds when copied over.

Fix error in seeds

---

app/views/concerts/show.html.erb
app/views/users/index.html.erb

Concert Show - Changed bad rails interpolation to correct ruby interpolation in the main header with artist links.

Fix Interpolation Error in Concert header

---

Procfile

Added Procfile to heopfully start heroku dyno.

Testing procfile

---

app/assets/stylesheets/application.css

header styling

---

app/views/concerts/_videos.html.erb

Changed the * like to a button_to so it can be targeted by ajax for disable.

Fix video display div/end

---

app/assets/stylesheets/concert-videos.css
app/views/concerts/_videos.html.erb

video styling
